# Generated by Django 5.1.2 on 2024-10-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_hangman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current_state',
        ),
    ]
