# Generated by Django 5.1.2 on 2024-10-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hangman', '0002_remove_game_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
